spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: saveit-project-467209        
          location: us-central1         
          chat:
            options:
              model: gemini-2.5-flash-lite       
              temperature: 0.5